### ISSUE TITLE
Grafana 8 dashboard error

### ISSUE THREAD

**Issue by Mondhund** [OpenBMP/obmp-grafana#2]
Hi,
with grafana 8 there are errors in some bar charts, e.g. top by prefixes: "failed to convert long to wide series when converting from dataframe: long series must be sorted ascending by time to be converted". This is an issue with the new version that is documented here: https://github.com/grafana/grafana/issues/35534

Thanks and regards - Thomas

**Comment by TimEvens** [comment]
@Mondhund,  can you try the latest release now?  It should resolve your issues.  I'll close this for now.
