### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by ankcn** [OpenBMP/obmp-grafana#3]
Hello!
There is no data in Grafana, while Postgres database keep growing.
Consumer Lag info:
 Partition    Lag    Latest Offset    Current Offset
-----------  -----  ---------------  ----------------
     7         0          30                30
     4         0          57                57
     0         0          18                18
     6         0          55                55
     2        22        3585991          3585969
     1         0          57                57
     3         0          60                60
     5         0          54                54
How to troubleshoot this issue?
Default installation (https://www.openbmp.org/getting_started.html).

Thank you!
Andrey

**Comment by TimEvens** [comment]
@ankcn , can you try the latest release now?  It should resolve your issues.  I'll close this for now.
